### ISSUE TITLE
Error with blobtools_create step

### ISSUE THREAD

**Issue by aureliendejode** [blobtoolkit/blobtoolkit#213]
Hello,

I have encountered the followinf error:
 more SHADDVT3_asm_bp_hap1_p_ctg/run_blobtools_create.log

Reading all TSV files in ../window_stats
Traceback (most recent call last):
  File "/share/apps/miniconda3/py311_23.5.2-0/installed/envs/snakemake7/bin/blobtools", line 8, in <module>
    sys.exit(cli())
  File "/share/apps/miniconda3/py311_23.5.2-0/installed/envs/snakemake7/lib/python3.9/site-packages/blobtools/blobtools.py", line 105, in cli
    sys.exit(subcommand())
  File "/share/apps/miniconda3/py311_23.5.2-0/installed/envs/snakemake7/lib/python3.9/site-packages/blobtools/lib/add.py", line 203, in cli
    main(args)
  File "/share/apps/miniconda3/py311_23.5.2-0/installed/envs/snakemake7/lib/python3.9/site-packages/blobtools/lib/add.py", line 149, in main
    parsed = field["module"].parse(
  File "/share/apps/miniconda3/py311_23.5.2-0/installed/envs/snakemake7/lib/python3.9/site-packages/blobtools/lib/busco.py", line 82, in parse
    busco = parse_busco(file, identifiers=kwargs["dependencies"]["identifiers"])
  File "/share/apps/miniconda3/py311_23.5.2-0/installed/envs/snakemake7/lib/python3.9/site-packages/blobtools/lib/busco.py", line 63, in parse_busco
    raise UserWarning(
UserWarning: Contig names in the Busco file did not match dataset identifiers.

I saw people having similar issue (e.g. #2) in the past but I did not see the fix for it.
In my case it looks like everything works fine for busco metazoa and eukaryota but for archaea and bacteria busco removed "_path" from the contigs id and I think that is what is causing the error.

zcat SHADDVT3_asm_bp_hap1_p_ctg.busco.bacteria_odb10/full_table.tsv.gz | head

 BUSCO version is: 5.6.1 
 The lineage dataset is: bacteria_odb10 (Creation date: 2020-03-06, number of genomes: 4085, number of BUSCOs: 124)
 Busco id	Status	Sequence	Gene Start	Gene End	Strand	Score	Length	OrthoDB url	Description
4421at2	Missing
9601at2	Missing
26038at2	Fragmented	h1tg000560l	68481	70196	+	151.4	265	https://www.orthodb.org/v10?query=26038at2	phosphoribosylformylglycinamidine synthase
91428at2	Missing
95696at2	Missing
143460at2	Missing
182107at2	Missing

Is there a fix to this or is it something that has to be done manually ?

Thanks for your help

**Comment by aureliendejode** [comment]
Hi,
Here are the headers for the fasta file (the assembly), they all have the following format:
>h1tg000309l_path
>h1tg000310l_path
>h1tg000311l_path
>h1tg000312l_path
>h1tg000313l_path
>h1tg000314l_path

They are contigs output from hifiasm assembly.

Then in the busco metazoa and eukaryota the contigs id are the same as in the fasta file:

270107at2759	Complete	h1tg000039l_path	1923850	1928544	+	617.0	599
271586at2759	Complete	h1tg000019l_path	3448379	3458776	+	297.6	389
290630at2759	Complete	h1tg000004l_path	2354527	2344837	-	543.9	461
293315at2759	Complete	h1tg000021l_path	1983882	1947754	-	509.3	559
296129at2759	Complete	h1tg000005l_path	2926981	2938826	+	954.7	708
299766at2759	Complete	h1tg000020l_path	9862506	9853025	-	495.8	436
306227at2759	Complete	h1tg000025l_path	9236278	9247485	+	542.8	459


For the archaea and bacteria the "_path" has been removed:
 26038at2	Fragmented	h1tg000560l	68481	70196	+	151.4	265	https://www.orthodb.org/v10?query=26038at2	phosphoribosylformylglycinamidine synthase
91428at2	Missing
95696at2	Missing
143460at2	Missing
182107at2	Missing
219876at2	Missing
223233at2	Fragmented	h1tg000118l	1228298	1230874	+	128.3	383	https://www.orthodb.org/v10?query=223233at2	DNA topoisomerase I


Hope that answer your question, let me know if you need more info.

Cheers
Aurélien

**Comment by aureliendejode** [comment]
Hi,
Have you found a fix for this ? 
Best
Aurélien

**Comment by rjchallis** [comment]
Looking at this more closely, it not straightforward to fix this in the BlobToolKit import code - the previous issue was with extra characters being added to the sequence IDs, but here they are removed so it is not as easy to put them back.

I think the best way would be a manual workaround either changing the sequence IDs in the assembly or editing the BUSCO file before import. To get the pipeline to run happily, you could also skip the bacteria and archaea lineages from the set of BUSCOs to run as these are usually included for use when exploring the results rather than required for the pipeline to run.

**Comment by aureliendejode** [comment]
Thanks for this. I'll just skip the bacteria and archaea lineages for now.
Best
Aurélien

**Comment by aureliendejode** [comment]
Hi,
I removed the bacteria and archaea lineages but then I ran into an error at the diamond_blastp step.
I think it is because I used "taxrule: blastp=buscogenes" for the tax rule.
How can I solve this issue. Should change the taxrule for the diamond_blastp step ?
Here is my config file:



`assembly:
  accession: SHADDVT3
  file: /grps2/bmtitus/analysis/Comparative_Genomic/Genome_assemblies/Stichodactyla_haddonii/blobtoolkit/SHADDVT3_asm_bp_hap1_p_ctg.fasta.gz
  level: contig
  prefix: SHADDVT3_asm_bp_hap1_p_ctg
  span: 459760080
busco:
  download_dir: /share/apps/genetic-databases/busco 
  basal_lineages:
    - eukaryota_odb10
    - bacteria_odb10
    - archaea_odb10
  lineages:
   - metazoa_odb10
   - eukaryota_odb10
reads:
  single:
   - file: /grps2/bmtitus/analysis/Comparative_Genomic/Genome_assemblies/Stichodactyla_haddonii/blobtoolkit/XBTUA20231220R84050PL40740011D01bc2031bc2031_hifireads.fastq.gz
     prefix: XBTUA20231220R84050PL40740011D01bc2031bc2031
     platform: PACBIO_SMRT
settings:
  blast_chunk: 100000
  blast_max_chunks: 10
  blast_min_length: 1000
  blast_overlap: 0
  stats_chunk: 1000
  stats_windows:
  - 0.1
  - 0.01
  - 100000
  - 1000000
  taxdump: /share/apps/genetic-databases/taxdump
  tmp: /tmp
similarity:
  blastn:
    name: nt
    path: /share/apps/genetic-databases/nt
  defaults:
    evalue: 1.0e-10
    import_evalue: 1.0e-25
    max_target_seqs: 10
    taxrule: bestsumorder
  diamond_blastp:
    import_max_target_seqs: 100000
    name: reference_proteomes
    path: /share/apps/genetic-databases/uniprot
    taxrule: blastp=buscogenes
  diamond_blast:
    name: reference_proteomes
    path: /share/apps/genetic-databases/uniprot
taxon:
  name: Stichodactyla haddoni

version: 2`

**Comment by rjchallis** [comment]
I think you may just need to remove bacteria and archaea from the `basal_lineages` section of the config as well

**Comment by aureliendejode** [comment]
Yes, it worked but I ran into another issue at the run_blobtools_create:

Reading all TSV files in ../window_stats
Loading parsed taxdump
Traceback (most recent call last):
  File "/share/apps/miniconda3/py311_23.5.2-0/installed/envs/snakemake7/bin/blobtools", line 8, in <module>
    sys.exit(cli())
  File "/share/apps/miniconda3/py311_23.5.2-0/installed/envs/snakemake7/lib/python3.9/site-packages/blobtools/blobtools.py", line 105, in cli
    sys.exit(subcommand())
  File "/share/apps/miniconda3/py311_23.5.2-0/installed/envs/snakemake7/lib/python3.9/site-packages/blobtools/lib/add.py", line 203, in cli
    main(args)
  File "/share/apps/miniconda3/py311_23.5.2-0/installed/envs/snakemake7/lib/python3.9/site-packages/blobtools/lib/add.py", line 149, in main
    parsed = field["module"].parse(
  File "/share/apps/miniconda3/py311_23.5.2-0/installed/envs/snakemake7/lib/python3.9/site-packages/blobtools/lib/hits.py", line 541, in parse
    blast = parse_blast(
  File "/share/apps/miniconda3/py311_23.5.2-0/installed/envs/snakemake7/lib/python3.9/site-packages/blobtools/lib/hits.py", line 54, in parse_blast
    seq_id, start, end = re.split(r"[:-]", parts[0])
ValueError: too many values to unpack (expected 3)


I have redownloaeded the newtaxdump to sure that this was not the issue.
Here is what I have in the taxdump folder:

-rw-r--r-- 1 adejode bmtitus 4,9K 14 mai   08:31 gencode.dmp
-rw-r--r-- 1 adejode bmtitus  452 14 mai   08:31 division.dmp
-rw-r--r-- 1 adejode bmtitus 3,0K 14 mai   08:37 typeoftype.dmp
-rw-r--r-- 1 adejode bmtitus 292M 14 mai   08:37 taxidlineage.dmp
-rw-r--r-- 1 adejode bmtitus 321M 14 mai   08:37 rankedlineage.dmp
-rw-r--r-- 1 adejode bmtitus 1,4M 14 mai   08:37 merged.dmp
-rw-r--r-- 1 adejode bmtitus 3,8M 14 mai   08:37 images.dmp
-rw-r--r-- 1 adejode bmtitus 691M 14 mai   08:37 fullnamelineage.dmp
-rw-r--r-- 1 adejode bmtitus 4,5M 14 mai   08:37 delnodes.dmp
-rw-r--r-- 1 adejode bmtitus 232M 14 mai   08:39 nodes.dmp
-rw-r--r-- 1 adejode bmtitus 217M 14 mai   08:40 names.dmp
-rw-r--r-- 1 adejode bmtitus  19M 14 mai   08:40 citations.dmp
-rw-r--r-- 1 adejode bmtitus  26M 14 mai   08:40 typematerial.dmp
-rw-r--r-- 1 adejode bmtitus 5,6M 14 mai   08:40 host.dmp
-rw-r--r-- 1 adejode bmtitus  44K 14 mai   08:40 excludedfromtype.dmp
-rw-r--r-- 1 adejode bmtitus 130M 14 mai   09:20 new_taxdump.tar.gz
-rw-r--r-- 1 adejode bmtitus   53 14 mai   09:20 new_taxdump.tar.gz.md5
-rw-r--r-- 1 adejode bmtitus 614M 14 mai   09:25 taxdump.json

It looks like some parsing issue for one of the file but I could not figure out which one.

Any idea ?




Here is my config file:

```
assembly:
  accession: SHADDVT3
  file: /grps2/bmtitus/analysis/Comparative_Genomic/Genome_assemblies/Stichodactyla_haddonii/blobtoolkit/SHADDVT3_asm_bp_hap1_p_ctg.fasta.gz
  level: contig
  prefix: SHADDVT3_asm_bp_hap1_p_ctg
  span: 459760080
busco:
  download_dir: /share/apps/genetic-databases/busco 
  basal_lineages:
   - eukaryota_odb10
  lineages:
   - metazoa_odb10
   - eukaryota_odb10
reads:
  single:
   - file: /grps2/bmtitus/analysis/Comparative_Genomic/Genome_assemblies/Stichodactyla_haddonii/blobtoolkit/XBTUA20231220R84050PL40740011D01bc2031bc2031_hifireads.fastq.gz
     prefix: XBTUA20231220R84050PL40740011D01bc2031bc2031
     platform: PACBIO_SMRT
settings:
  blast_chunk: 100000
  blast_max_chunks: 10
  blast_min_length: 1000
  blast_overlap: 0
  stats_chunk: 1000
  stats_windows:
  - 0.1
  - 0.01
  - 100000
  - 1000000
  taxdump: /grps2/bmtitus/databases/taxdump
  tmp: /tmp
similarity:
  blastn:
    name: nt
    path: /share/apps/genetic-databases/nt
  defaults:
    evalue: 1.0e-10
    import_evalue: 1.0e-25
    max_target_seqs: 10
    taxrule: bestsumorder
  diamond_blastp:
    import_max_target_seqs: 100000
    name: reference_proteomes
    path: /share/apps/genetic-databases/uniprot
    taxrule: blastp=buscogenes
  diamond_blastx:
    name: reference_proteomes
    path: /share/apps/genetic-databases/uniprot
taxon:
  name: Stichodactyla haddoni

version: 2

```
